Sprint2b
Iker-elorrieta/RetoADPSP2 pull request #2
Opened 2021-01-14 18:41 UTC by jon2lla

Version Estable Sprint 2. Compatible con CafrometAndroid v1.1

2021-01-15 10:33 UTC, Iker-elorrieta requested changes
No puedo ejecutar el proyecto:

He cambiado la IP a la que se conecta el cliente.
He descomentado la carga previa de los datos.
He creado la base de datos.
Hay un problema de consistencia en los centro meteorológicos. No corresponde la base de datos que habéis subido con el modelo del proyecto.

No puede ser el centro meteorológico aparezca : 
	private String municipio;
	private String provincia;

Debería aparecer solo en municipio y además como objeto no como String. De hay los errores que da el proyecto. No muestra nada el cliente y las pruebas llegan al 50%.

Hay que tener cuidado a la hora de entregar, entregar algo estable y que sea desplegable con todas sus funcionalidades.

2021-01-15 10:42 UTC, jon2lla commented
Apa iker,

Puede ser que hayas corrido el archivo .sql en vez de el .txt?

Fallo mio, creo que ese fichero esta sin actualizar por problemas que
tuvimos el dia anterior con el control de versiones.

La BBDD que funciona correctamente es la de el fichero .txt.

Agur ta barkatu eragozpenak,

Jon

El vie., 15 ene. 2021 11:33, Iker-elorrieta <notifications@github.com>
escribió:

> *@Iker-elorrieta* requested changes on this pull request.
>
> No puedo ejecutar el proyecto:
>
> He cambiado la IP a la que se conecta el cliente.
> He descomentado la carga previa de los datos.
> He creado la base de datos.
> Hay un problema de consistencia en los centro meteorológicos. No
> corresponde la base de datos que habéis subido con el modelo del proyecto.
>
> No puede ser el centro meteorológico aparezca :
> private String municipio;
> private String provincia;
>
> Debería aparecer solo en municipio y además como objeto no como String. De
> hay los errores que da el proyecto. No muestra nada el cliente y las
> pruebas llegan al 50%.
>
> Hay que tener cuidado a la hora de entregar, entregar algo estable y que
> sea desplegable con todas sus funcionalidades.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Iker-elorrieta/RetoADPSP2/pull/2#pullrequestreview-569143263>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOKSVVOOKHBCU7F5IRZHQOLS2AKYPANCNFSM4WC3MMTQ>
> .
>

2021-01-15 11:53 UTC, Iker-elorrieta requested changes
1-. Para que no pase el problema de la BD, hay que poner solo un archivo. Insisto en dejarlo preparado para su correcto funcionamiento en cualquier equipo.
2-.Las pruebas en mi equipo dan 79,6. Algun error que me sale en las pruebas es:
java.io.FileNotFoundException: src\resource\com\cafromet\files\temp\src\resource\com\cafromet\files\json\pueblos.json (El sistema no puede encontrar la ruta especificada)

No se debe de crear o algo parecido.

3-. El objeto que se envía al cliente es el DTO y no el objeto de Hibernate. Como os comente esto solo debería ser si la petición se realiza desde el móvil.
4-. Sobre el código os he puesto alguna que otra apreciación.

2021-01-15 11:53 UTC, Iker-elorrieta commented on src/main/java/com/cafromet/server/IOListenerSrv.java
> +			for(Municipio muni : lista) {
Sobran estas lineas

2021-01-15 11:53 UTC, Iker-elorrieta commented on src/main/java/com/cafromet/server/Updater.java
> +		fuenteMunicipios.setFormato(".json");
.json se repite muchas veces

2021-01-15 11:53 UTC, Iker-elorrieta commented on src/main/java/com/cafromet/util/GestorFicheros.java
> +				} else if (entrada.getKey().equals("provincia")) {
String que deberían ser final

2021-01-15 11:53 UTC, Iker-elorrieta commented on src/main/java/com/cafromet/util/GestorFicheros.java
> +		} else if (elemento.isJsonArray()) {
Esta parte se repite en todos los procesados ¿Se puede meter en una función?

2021-01-19 22:37 UTC, Iker-elorrieta requested changes
83% en las pruebas.
Aparecen las IP y no localhost como deberia aparecer ( Lo he tenido que cambiar).
El cliente no funciona por una linea.
Revisando la BD las mediciones no estan relacionadas con los municipios y deberian estarlo. Hay que cambiar las tablas.

2021-01-19 22:37 UTC, Iker-elorrieta commented on src/main/java/com/cafromet/cliente/ControladorVentanMunicipio.java
> +			System.out.println(municipios.get(2).getProvincia().getMunicipios());
Esta linea genera el error en el cliente

2021-01-20 22:35 UTC, merged